# Generated by Django 4.2.1 on 2023-05-31 00:35

from django.db import migrations, models
import user_services.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user_services.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email_address"
            ),
        ),
    ]
