# Generated by Django 4.2.1 on 2023-06-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_service", "0001_initial"),
        ("user_services", "0002_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="borrowed_books",
            field=models.ManyToManyField(
                blank=True, related_name="borrowed_by", to="book_service.book"
            ),
        ),
    ]
