# Generated by Django 4.2.1 on 2023-06-16 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow", models.DateTimeField(auto_now_add=True)),
                (
                    "expected_return_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 6, 23, 18, 0, 46, 79523, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                    ),
                ),
                ("actual_return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "ordering": ["actual_return_date"],
            },
        ),
    ]
