# Generated by Django 4.2.1 on 2023-06-17 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 24, 19, 5, 16, 481361, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
