# Generated by Django 4.2.1 on 2023-06-09 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="payment_type",
        ),
    ]
