# Generated by Django 4.2.1 on 2023-06-13 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow", models.DateTimeField(auto_now_add=True)),
                (
                    "expected_return_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            6,
                            20,
                            23,
                            36,
                            25,
                            892472,
                            tzinfo=datetime.timezone.utc,
                        ),
                        editable=False,
                    ),
                ),
                ("actual_return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_service.book",
                    ),
                ),
            ],
            options={
                "ordering": ["actual_return_date"],
            },
        ),
    ]
