# Generated by Django 4.2.1 on 2023-06-01 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 8, 17, 14, 44, 440427, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
