# Generated by Django 4.2.1 on 2023-06-03 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing_service", "0002_alter_borrowing_expected_return_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["actual_return_date"]},
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 10, 13, 45, 59, 584543, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
