# Generated by Django 4.2.1 on 2023-06-07 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing_service", "0003_alter_borrowing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 14, 0, 37, 35, 630793, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
